In [2]:
import numpy as np

mathScoreNestedList = [[11,12,13],[21,22,23],[31,32,33]]
mathScoreNdarray = np.array(mathScoreNestedList)

print(mathScoreNdarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
mathScoreNdarray

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
mathScoreNdarray + 1 #브로드캐스팅

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [5]:
np.sum(mathScoreNdarray)

198

In [6]:
np.average(mathScoreNdarray)

22.0

열의 평균 구하기

In [7]:
np.average(mathScoreNdarray, axis = 0)

array([21., 22., 23.])

행의 평균 구하기

In [8]:
np.average(mathScoreNdarray, axis = 1)

array([12., 22., 32.])

In [9]:
x = np.array([[1,2],[3,4]], dtype = np.int8)
y = x.T

stride 개념 공부하기; 전치할 때 계산이 빠른 건가봐

In [10]:
#산술평균
np.mean(range(1,11))
#가중평균
np.average(range(1,11))

5.5

In [11]:
from tensorflow.python.client.device_lib import list_local_devices

list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 5160748908035267527,
 name: "/device:GPU:0"
 device_type: "GPU"
 locality {
   bus_id: 1
 }
 incarnation: 17689386980219148821
 physical_device_desc: "device: 0, name: METAL, pci bus id: <undefined>"]

<!-- <details> -->
<!-- <summary>다차원 배열 생성1</summary> -->
<!-- <div markdown="1" css="display:flex; align-items:center"> -->
다차원 배열의 원소는 위와 같은 데이터 타입을 가질 수 있음
다차원 배열의 원소는 동일한 데이터 타입을 가져야 함
<img src="https://numpy.org/doc/stable/_images/dtype-hierarchy.png"/>
<!-- </div> -->
<!-- </details> -->

<h1>직접 원소를 입력해서 다차원 배열 생성하기</h1> 

np.array()를 사용해서 다차원 배열을 만들 수 있다.

<h2>bool</h2>

In [12]:
boolArray = np.array([True, False, True, True, False])
boolArray

array([ True, False,  True,  True, False])

In [13]:
boolArray.dtype

dtype('bool')

<h2>number</h2>

number에는 int, unsigned int, float, double형이 있음

int형

In [14]:
intArray = np.array([[1,2],[3,4]])
intArray

array([[1, 2],
       [3, 4]])

int형의 default data type은 'int64'

In [15]:
intArray.dtype

dtype('int64')

unsigned int형

In [16]:
uintArray = np.array([[1, 2], [3, 4]], dtype = 'uint')
uintArray

array([[1, 2],
       [3, 4]], dtype=uint64)

uint형의 default data type은 'uint64'

In [17]:
uintArray.dtype

dtype('uint64')

float

In [18]:
floatArray = np.array([[1.1,2.2],[3.3,4.4]])
floatArray

array([[1.1, 2.2],
       [3.3, 4.4]])

float형의 default data type은 'float64'


In [19]:
floatArray.dtype

dtype('float64')

데이터가 정수로 입력되더라도 data type을 실수형으로 명시한다면 실수형으로 자동 형변환이 일어남

In [20]:
floatArray2 = np.array([[1,2],[3,4]], dtype='float64' )
floatArray2.dtype

dtype('float64')

사실 위 방법보다는 실수형 데이터를 가지고 있는 다차원 배열을 만들고 싶다면 아래와 같이 하는 것이 더 나은 코딩표준임

In [21]:
floatArray3 = np.array([[1.,2.],[3.,4.]])
floatArray3.dtype

dtype('float64')

(참고)복소수형 -> 혹시나 언젠가 파동함수로부터 데이터를 다룰 일이 생길 수도 있으니까

In [22]:
complexArray = np.array([1+1j,2+2j,3+3j,4+4j])
complexArray

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [23]:
complexArray.dtype

dtype('complex128')

<h1>파일에서 데이터를 입력받아 다차원 배열 생성하기</h1>

np.genfromtxt()를 이용하여 파일에 저장된 데이터를 입력받아 다차원 배열을 생성할 수 있으나,  
사용할 일이 많지 않다. 그 이유는
* Numpy ndarray는 동일한 데이터 타입만 가질 수 있는데
* 대부분의 데이터 파일에는 하나의 데이터 타입만 있는게 아니라 정수, 실수, 문자열이 섞여 있다.  

주로 파일에서 데이터를 읽어올 때는 ***___Pandas의 read_csv()나 read_excel()을 주로 사용함___***

<h1>Numpy.empty</h1>

return a new array of given shape and type, without initializing entiries.

In [24]:
np.empty((2,3))

array([[0.  , 0.15, 0.25],
       [0.5 , 0.75, 1.  ]])

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
#형태를 그대로 베끼되 초기화는 하지 않은 배열을 반환함
np.empty_like(A)

array([[                  0,                  90,                   0],
       [                  0,                   0, 7149574567489843301],
       [3833738903055120685, 3258125843396649526, 4048799163330474800]])

하지만, 초기화를 하지 않은 상태의 배열을 필요로 하는 상황은 그다지 많지 않고 0으로 초기화를 보통한다. 따라서 <u>numpy.zeros</u> 를 사용한다.

<h1>numpy.zeros</h1>

Return a new array of given shape and type, filled with zeros.

보이는 것과 같이 default type은  float64이다.

In [27]:
np.zeros((2,3)).dtype

dtype('float64')

In [28]:
np.zeros((2,3), dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<h1>numpy.ones</h1>

Return a new array of given shape and type, filled with ones.

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

마찬가지로 default type는 float64이다.

In [31]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

<h1>numpy.identity</h1>

Return the identity array(단위행렬)

In [33]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.identity(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<h2>참고</h2>

<h3>numpy.eye</h3>

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [38]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

<h2>numpy.full</h2>

numpy.full(shape, fill_value, dtype = None, order = 'C')
Return a new array of given shape and type, filled with fill_value.

In [40]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

위보다는 아래 방식을 선호함(ones함수가 보통 익숙함)

In [41]:
10*np.ones((2,3), dtype = int)

array([[10, 10, 10],
       [10, 10, 10]])

<h2>numpy.arange</h2>

Return evenly spaced values within a given interval.

In [42]:
#default value
#start = 0
#step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(1,5,0.5)


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<h2>numpy.linspace</h2>

Return evenly spaced numbers over a specified interval.

In [44]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcvwJj4%2FbtqBvtZ3zhm%2Fof7j5W7tvanDZ3jq9GiuT0%2Fimg.png" css="height: 600px;width:600px">

<h1>통계값 구해보기</h1>
<h2>보통 pandas에서 사용</h2>

<h2>numpy.amin</h2>

Return the minimum of an array of minimum along an axis.

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#(axis에 맞추어 최소값 찾는 함수)
np.amin(A,0)

array([1, 2, 3])

In [48]:
np.amin(A,1)

array([1, 4, 7])

In [49]:
np.amin(A)

1

<h2>numpy.amax</h2>

Return the maximum of an array or maximum along an axis.

완전 반대이므로 생략

<h2>numpy.ptp</h2>

Range of values(maximum-minimum) along an axis.  
The name of the function comes from the acronym for 'peak to peak'.  

In [50]:
np.ptp(A,0)

array([6, 6, 6])

In [52]:
np.ptp(A,0)

array([6, 6, 6])

In [51]:
np.ptp(A,1)

array([2, 2, 2])

<h1>numpy.media</h1>

Compute the median along the specified axis.

In [53]:
np.median(A,0)

array([4., 5., 6.])

In [54]:
np.median(A,1)

array([2., 5., 8.])

In [55]:
np.median(A)

5.0

<h1>분산(var),표준편차(std)</h1>

numpy.var  
numpy.std

In [56]:
np.var(A,0)

array([6., 6., 6.])

In [57]:
np.var(A)

6.666666666666667

In [59]:
np.std(A,1)

array([0.81649658, 0.81649658, 0.81649658])

In [58]:
np.std(A)

2.581988897471611