In [2]:
import numpy as np

mathScoreNestedList = [[11,12,13],[21,22,23],[31,32,33]]
mathScoreNdarray = np.array(mathScoreNestedList)

print(mathScoreNdarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:
mathScoreNdarray

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
mathScoreNdarray + 1 #브로드캐스팅

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [5]:
np.sum(mathScoreNdarray)

198

In [6]:
np.average(mathScoreNdarray)

22.0

열의 평균 구하기

In [7]:
np.average(mathScoreNdarray, axis = 0)

array([21., 22., 23.])

행의 평균 구하기

In [8]:
np.average(mathScoreNdarray, axis = 1)

array([12., 22., 32.])

In [9]:
x = np.array([[1,2],[3,4]], dtype = np.int8)
y = x.T

stride 개념 공부하기; 전치할 때 계산이 빠른 건가봐

In [10]:
#산술평균
np.mean(range(1,11))
#가중평균
np.average(range(1,11))

5.5

In [11]:
from tensorflow.python.client.device_lib import list_local_devices

list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 9871427343004271112,
 name: "/device:GPU:0"
 device_type: "GPU"
 locality {
   bus_id: 1
 }
 incarnation: 3835919719068112026
 physical_device_desc: "device: 0, name: METAL, pci bus id: <undefined>"]

<!-- <details> -->
<!-- <summary>다차원 배열 생성1</summary> -->
<!-- <div markdown="1" css="display:flex; align-items:center"> -->
다차원 배열의 원소는 위와 같은 데이터 타입을 가질 수 있음
다차원 배열의 원소는 동일한 데이터 타입을 가져야 함
<img src="https://numpy.org/doc/stable/_images/dtype-hierarchy.png"/>
<!-- </div> -->
<!-- </details> -->

<h1>직접 원소를 입력해서 다차원 배열 생성하기</h1> 

<h2>bool</h2>

In [12]:
boolArray = np.array([True, False, True, True, False])
boolArray

array([ True, False,  True,  True, False])

In [13]:
boolArray.dtype

dtype('bool')

<h2>number</h2>

number에는 int, unsigned int, float, double형이 있음

int형

In [14]:
intArray = np.array([[1,2],[3,4]])
intArray

array([[1, 2],
       [3, 4]])

int형의 default data type은 'int64'

In [15]:
intArray.dtype

dtype('int64')

unsigned int형

In [16]:
uintArray = np.array([[1, 2], [3, 4]], dtype = 'uint')
uintArray

array([[1, 2],
       [3, 4]], dtype=uint64)

uint형의 default data type은 'uint64'

In [17]:
uintArray.dtype

dtype('uint64')

float

In [18]:
floatArray = np.array([[1.1,2.2],[3.3,4.4]])
floatArray

array([[1.1, 2.2],
       [3.3, 4.4]])

float형의 default data type은 'float64'


In [19]:
floatArray.dtype

dtype('float64')

데이터가 정수로 입력되더라도 data type을 실수형으로 명시한다면 실수형으로 자동 형변환이 일어남

In [25]:
floatArray2 = np.array([[1,2],[3,4]], dtype='float64' )
floatArray2.dtype

dtype('float64')

사실 위 방법보다는 실수형 데이터를 가지고 있는 다차원 배열을 만들고 싶다면 아래와 같이 하는 것이 더 나은 코딩표준임

In [24]:
floatArray3 = np.array([[1.,2.],[3.,4.]])
floatArray3.dtype

dtype('float64')

(참고)복소수형 -> 혹시나 언젠가 파동함수로부터 데이터를 다룰 일이 생길 수도 있으니까

In [26]:
complexArray = np.array([1+1j,2+2j,3+3j,4+4j])
complexArray

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [27]:
complexArray.dtype

dtype('complex128')