In [61]:
import numpy as np

mathScoreNestedList = [[11,12,13],[21,22,23],[31,32,33]]
mathScoreNdarray = np.array(mathScoreNestedList)

print(mathScoreNdarray)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [62]:
mathScoreNdarray

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [63]:
mathScoreNdarray + 1 #브로드캐스팅

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [64]:
np.sum(mathScoreNdarray)

198

In [65]:
np.average(mathScoreNdarray)

22.0

열의 평균 구하기

In [66]:
np.average(mathScoreNdarray, axis = 0)

array([21., 22., 23.])

행의 평균 구하기

In [67]:
np.average(mathScoreNdarray, axis = 1)

array([12., 22., 32.])

In [68]:
x = np.array([[1,2],[3,4]], dtype = np.int8)
y = x.T

stride 개념 공부하기; 전치할 때 계산이 빠른 건가봐

In [69]:
#산술평균
np.mean(range(1,11))
#가중평균
np.average(range(1,11))

5.5

In [70]:
from tensorflow.python.client.device_lib import list_local_devices

list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 9607077867182170726,
 name: "/device:GPU:0"
 device_type: "GPU"
 locality {
   bus_id: 1
 }
 incarnation: 11182981982108526485
 physical_device_desc: "device: 0, name: METAL, pci bus id: <undefined>"]

<!-- <details> -->
<!-- <summary>다차원 배열 생성1</summary> -->
<!-- <div markdown="1" css="display:flex; align-items:center"> -->
다차원 배열의 원소는 위와 같은 데이터 타입을 가질 수 있음
다차원 배열의 원소는 동일한 데이터 타입을 가져야 함
<img src="https://numpy.org/doc/stable/_images/dtype-hierarchy.png"/>
<!-- </div> -->
<!-- </details> -->

<h1>직접 원소를 입력해서 다차원 배열 생성하기</h1> 

np.array()를 사용해서 다차원 배열을 만들 수 있다.

<h2>bool</h2>

In [71]:
boolArray = np.array([True, False, True, True, False])
boolArray

array([ True, False,  True,  True, False])

In [72]:
boolArray.dtype

dtype('bool')

<h2>number</h2>

number에는 int, unsigned int, float, double형이 있음

int형

In [73]:
intArray = np.array([[1,2],[3,4]])
intArray

array([[1, 2],
       [3, 4]])

int형의 default data type은 'int64'

In [74]:
intArray.dtype

dtype('int64')

unsigned int형

In [75]:
uintArray = np.array([[1, 2], [3, 4]], dtype = 'uint')
uintArray

array([[1, 2],
       [3, 4]], dtype=uint64)

uint형의 default data type은 'uint64'

In [76]:
uintArray.dtype

dtype('uint64')

float

In [77]:
floatArray = np.array([[1.1,2.2],[3.3,4.4]])
floatArray

array([[1.1, 2.2],
       [3.3, 4.4]])

float형의 default data type은 'float64'


In [78]:
floatArray.dtype

dtype('float64')

데이터가 정수로 입력되더라도 data type을 실수형으로 명시한다면 실수형으로 자동 형변환이 일어남

In [79]:
floatArray2 = np.array([[1,2],[3,4]], dtype='float64' )
floatArray2.dtype

dtype('float64')

사실 위 방법보다는 실수형 데이터를 가지고 있는 다차원 배열을 만들고 싶다면 아래와 같이 하는 것이 더 나은 코딩표준임

In [80]:
floatArray3 = np.array([[1.,2.],[3.,4.]])
floatArray3.dtype

dtype('float64')

(참고)복소수형 -> 혹시나 언젠가 파동함수로부터 데이터를 다룰 일이 생길 수도 있으니까

In [81]:
complexArray = np.array([1+1j,2+2j,3+3j,4+4j])
complexArray

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [82]:
complexArray.dtype

dtype('complex128')

<h1>파일에서 데이터를 입력받아 다차원 배열 생성하기</h1>

np.genfromtxt()를 이용하여 파일에 저장된 데이터를 입력받아 다차원 배열을 생성할 수 있으나,  
사용할 일이 많지 않다. 그 이유는
* Numpy ndarray는 동일한 데이터 타입만 가질 수 있는데
* 대부분의 데이터 파일에는 하나의 데이터 타입만 있는게 아니라 정수, 실수, 문자열이 섞여 있다.  

주로 파일에서 데이터를 읽어올 때는 ***___Pandas의 read_csv()나 read_excel()을 주로 사용함___***

<h1>Numpy.empty</h1>

return a new array of given shape and type, without initializing entiries.

In [83]:
np.empty((2,3))

array([[5.e-324, 5.e-324, 5.e-324],
       [5.e-324, 5.e-324, 5.e-324]])

In [84]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
#형태를 그대로 베끼되 초기화는 하지 않은 배열을 반환함
np.empty_like(A)

array([[                  0,                 173,                   0],
       [                  0,        519691042816, 7149574567489843301],
       [3833738903055120685, 3258125843396649526, 4048799163330474800]])

하지만, 초기화를 하지 않은 상태의 배열을 필요로 하는 상황은 그다지 많지 않고 0으로 초기화를 보통한다. 따라서 <u>numpy.zeros</u> 를 사용한다.

<h1>numpy.zeros</h1>

Return a new array of given shape and type, filled with zeros.

보이는 것과 같이 default type은  float64이다.

In [86]:
np.zeros((2,3)).dtype

dtype('float64')

In [87]:
np.zeros((2,3), dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<h1>numpy.ones</h1>

Return a new array of given shape and type, filled with ones.

In [89]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

마찬가지로 default type는 float64이다.

In [90]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

<h1>numpy.identity</h1>

Return the identity array(단위행렬)

In [91]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [92]:
np.identity(3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<h2>참고</h2>

<h3>numpy.eye</h3>

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [95]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

<h2>numpy.full</h2>

numpy.full(shape, fill_value, dtype = None, order = 'C')
Return a new array of given shape and type, filled with fill_value.

In [97]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

위보다는 아래 방식을 선호함(ones함수가 보통 익숙함)

In [98]:
10*np.ones((2,3), dtype = int)

array([[10, 10, 10],
       [10, 10, 10]])

<h2>numpy.arange</h2>

Return evenly spaced values within a given interval.

In [99]:
#default value
#start = 0
#step = 1
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(1,5,0.5)


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

<h2>numpy.linspace</h2>

Return evenly spaced numbers over a specified interval.

In [101]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

<img src="https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FcvwJj4%2FbtqBvtZ3zhm%2Fof7j5W7tvanDZ3jq9GiuT0%2Fimg.png" style="width:600px">

<h1>통계값 구해보기</h1>
<h2>보통 pandas에서 사용</h2>

<h2>numpy.amin</h2>

Return the minimum of an array of minimum along an axis.

In [102]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
#(axis에 맞추어 최소값 찾는 함수)
np.amin(A,0)

array([1, 2, 3])

In [104]:
np.amin(A,1)

array([1, 4, 7])

In [105]:
np.amin(A)

1

<h2>numpy.amax</h2>

Return the maximum of an array or maximum along an axis.

완전 반대이므로 생략

<h2>numpy.ptp</h2>

Range of values(maximum-minimum) along an axis.  
The name of the function comes from the acronym for 'peak to peak'.  

In [106]:
np.ptp(A,0)

array([6, 6, 6])

In [107]:
np.ptp(A,0)

array([6, 6, 6])

In [108]:
np.ptp(A,1)

array([2, 2, 2])

<h1>numpy.median</h1>

Compute the median along the specified axis.

In [109]:
np.median(A,0)

array([4., 5., 6.])

In [110]:
np.median(A,1)

array([2., 5., 8.])

In [111]:
np.median(A)

5.0

<h1>분산(var),표준편차(std)</h1>

numpy.var  
numpy.std

In [112]:
np.var(A,0)

array([6., 6., 6.])

In [113]:
np.var(A)

6.666666666666667

In [114]:
np.std(A,1)

array([0.81649658, 0.81649658, 0.81649658])

In [115]:
np.std(A)

2.581988897471611

<h1>슬라이싱</h1>

다차원 배열은 아래와 같은 방법으로 슬라이싱함  
a[  :  ,  :  ]  
a[행 슬라이싱 시작: 행 슬라이싱 끝, 열 슬라이싱 시작: 열 슬라이싱 끝]  
**시작값** 부터 **끝값** <span style = "color:red">전</span>까지 슬라이싱됨

시작값이 0인 경우 생략 가능하며 끝 값이 shape의 값과 동일한 경우 생략 가능함

In [117]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a[0:2, 0:4]
#==a[:2,:4]==a[:2,:]==a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<h1>인덱싱</h1>

인덱싱을 통해 원소에 접근 가능  
두 가지 표현법이 있음

In [ ]:
#선호하는 방식
a[0,0]

In [ ]:
a[0][0] #통일성이 없어서 별로 안 좋음

Numpy 배열을 슬라이싱하면, 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열임  
그러나 인덱싱을 한다면, 연속하지 않은 값을 가져올 수 있으니 원본과 다른 배열을 만들 수 있음

In [118]:
#0행과 2행만 인덱싱
a[[0,2],]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [119]:
#0열, 1열, 3열만 인덱싱
a[:, [0,1,3]]

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [121]:

#! 슬라이싱만 사용
slicedRow = a[0:1, :]
print(slicedRow,slicedRow.shape,slicedRow.ndim)

[[1 2 3 4]] (1, 4) 2


In [122]:
#아래와 동일한 코드
#! 인덱싱&슬라이싱 혼합 사용
#@ 차원이 줄어듬!!!!
indexedRow = a[0]
print(indexedRow, indexedRow.shape, indexedRow.ndim)

#위와 동일한 코드
#! 인덱싱&슬라이싱 혼합 사용
#@ 차원이 줄어듬!!!!
indexedRow2 = a[0, :]
print(indexedRow2, indexedRow2.shape, indexedRow2.ndim)

[1 2 3 4] (4,) 1
[1 2 3 4] (4,) 1


행이 아닌 열의 경우에도 마찬가지

In [123]:

#! 슬라이싱만 사용
#@ 잘 보면 col형태가 살아있는 것을 확인할 수 있음
slicedCol = a[:, 0:1]
print(slicedCol, slicedCol.shape, slicedCol.ndim)

[[1]
 [5]
 [9]] (3, 1) 2


In [124]:

#아래와 동일한 코드
#! 인덱싱&슬라이싱 혼합 사용
indexedCol = a[:, 0]
print(indexedCol, indexedCol.shape, indexedCol.ndim)

#위와 동일한 코드
#! 인덱싱&슬라이싱 혼합 사용
indexedCol2 = a[:, 0]
print(indexedCol2, indexedCol2.shape, indexedCol2.ndim)

[1 5 9] (3,) 1
[1 5 9] (3,) 1


다차원 배열간 연산에서 차원이 달라 문제가 발생하는 경우가 종종 있음  
**특별히 인덱싱을 써야 하는 상황이 아니라면, 인덱싱보다 슬라이싱을 추천**

<h1>인덱싱&슬라이싱 - 값 복사&참조</h1>

인덱싱은 값을 복사해옴, 복사된 값을 변경해도 원본의 값은 변하지 않음

In [126]:
# 인덱싱해서 b에 대입
b = a[0, 0]

#b값 수정
b = 100

print("a[0,0]: {}".format(a[0,0]))
print("b: {}".format(b))

a[0,0]: 1
b: 100


슬라이싱된 배열은 원본 배열과 같은 데이터를 참조  
<span style="color: red">즉 슬라이싱된 배열을 수정하면 원본 배열 역시 수정됨</span>

In [127]:
#a를 슬라이스하여 c 생성
c = a[1:3, 1:3]

print(c)

[[ 6  7]
 [10 11]]


In [128]:
#c[0,0]은 a[1, 1]과 같은 데이터
c[0, 0] = 100

print(c)
print('------------------')
print(a)

[[100   7]
 [ 10  11]]
------------------
[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


슬라이싱은 값을 참조하기 때문에 주소만 가져오므로 ***속도가 빠름***  
반면에 인덱싱은 값을 복사하기 때문에 ***속도가 느림***

<h1>불리언 배열 인덱싱</h1>

불리언 배열 인덱싱을 통해 배열 속 요소를 취사선택할 수 있음  
불리언 배열 인덱싱은 특정 조건을 만족하게 하는 요소만 선택하고자 할 때 자주 사용됨

In [129]:
a = np.array([[1,2],[3,4],[5,6]])

print(a)

[[1 2]
 [3 4]
 [5 6]]


In [131]:
bool_idx = (a>2)
#@ 2보다 큰 a의 요소를 찾음
#@ 이 코드는 a와 shape가 같고 불리언 자료형을 요소로 하는 numpy 배열을 반환함
#@ bool_idx의 각 요소는 동일한 위치에 있는 a의
#@ 요소가 2보다 큰지를 말해줌

print(bool_idx)

#! 불리언 배열 인덱싱을 통해 bool_idx에서
#! 참값을 가지는 요소로 구성되는 
#! Rank가 1인 배열을 구성할 수 있음
print(a[bool_idx])

#* 위에서 한 모든 것을 한 문장으로 할 수 있음
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


<h1>(참조) 정수형 배열 인덱싱</h1>

In [132]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [135]:
#정수 배열 인덱싱의 예
#반환되는 배열의 shape는 (3,)
print(a[[0,1,2],[0,1,0]]) #(0,0),(1,1),(2,0)을 가져와라

#위에서 본 정수 배열 인덱싱 예제는 다음과 동일
print(np.array([a[0,0],a[1,1],a[2,0]]))

#정수 배열 인덱싱을 사용할 떄
#원본 배열의 같은 요소를 재사용할 수 있음
print(a[[0,0],[1,1]]) #(0,1), (0,1)

#위 예제는 다음과 동일
print(np.array(a[0, 1],a[0, 1]))

[1 4 5]
[1 4 5]
[2 2]
2


<h1>전치(transpose)</h1>


In [137]:
x = np.array([[1,2],[3,4]])
print(x.T)

#차원이 1인 배열을 전치할 경우 아무 일도 일어나지 않음
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


<h1>Shape 변경</h1>

<h2>numpy.reshape</h2>

Gives a new shape to an array without changing its data

In [138]:

#@ 가장 일반적인 것이 reshape임
#! rank가 1이던 배열이 3x2 배열로 바뀜
a = np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [140]:

#@ 또다른 활용
np.reshape(a,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:

#! 이렇게 차원을 바꾸는 것을 권장
np.reshape(a,(1,6))

#* 이거는 비추
np.reshape(a, 6)

array([0, 1, 2, 3, 4, 5])

<h2>numpy.ravel()</h2>

Return a contiguous flattened array.  
<span style = "color: red">Ravel은 (실을) 풀다 라는 뜻임</span>
flatten()함수와 비슷함

In [143]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5])

이미지를 다룰 때 사용함

In [144]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

<h1>numpy.ndarray.flatten()</h1>

Return a copy of the array collapsed into one dimension.

In [145]:

#! np.flatten(a) 이런 식으로 사용할 수 없음(Numpy 모듈 함수가 아님)
a.flatten()  #@ ndarray 객체의 메소드로만 사용 가능

array([0, 1, 2, 3, 4, 5])

**ravel()과 flatten()의 차이점**
* flatten()은 객체의 메소드로만 사용 가능
* ravel()은 뷰를 반환 flatten()은 복사본을 반환

<h1>연결</h1>

<h2>numpy.cancatenate()</h2>

In [148]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [149]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

<h2>참조</h2>

<a href = "https://numpy.org/doc/stable/reference/routines.array-manipulation.html">참조</a>

<h1>다차원 배열 연산</h1>

기본적인 수학함수는 배열의 각 요소별로 동작하며 연사자를 통해 동작하거나 numpy 함수 모듈을 통해 동작함  
다차원 배열간 연산시, **shape가 맞아야** 연산이 이루어짐  
* 요소별 합, 차, 곱, 나눗셈의 경우 shape가 일치해야 함
* dot의 경우 앞 배열의 열과 뒤 배열의 행의 크기가 일치해야 함

<a href="https://docs.scipy.org/doc/numpy/reference/routines.math.html">reference</a>

In [152]:
x = np.array([[1.,2.],[3.,4.]])
y = np.array([[5.,6.],[7.,8.]])

# 요소별 합
print(x+y)
print(np.add(x,y))

# 요소별 차
print(x-y)
print(np.subtract(x,y))

#요소별 곱
print(x*y)
print(np.multiply(x,y))

#요소별 나눗셈
print(x/y)
print(np.divide(x,y))

#요소별 제곱근
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


numpy에선 벡터의 내적, 벡터와 행렬의 곱, 행렬 곱을 위해 * 대신 dot함수를 사용함
dot은 numpy 모듈 함수로서도 배열 객체의 메소드로서도 이용 가능한 함수

In [153]:
v = np.array([9,10])
w = np.array([11,12])

#벡터의 내적
print(v.dot(w))
print(np.dot(v,w))

#행렬과 벡터의 곱
print(x.dot(v))
print(np.dot(x,v))

#행렬곱
print(x.dot(y))
print(np.dot(x,y))

219
219
[29. 67.]
[29. 67.]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


<h1>numpy 고급 기능</h1>

브로드캐스팅은 Numpy에서 shape가 다른 배열 간에도 산술 연산이 가능하게 하는 메커니즘, 종종 작은 배열과 큰 배열이 있을 떄, 큰 배열을 대상으로 작은 배열을 여러 번 연산하고자 할 때가 있음  
예를 들어, 행렬의 각 행에 상수 벡터를 더할 때 사용함

In [154]:
 #! 행렬 x의 각 행에 벡터 v를 더한 뒤, 그 결과를 행렬 y에 저장하고자 할 때 보통 반복문을 사용해서 다음과 같이 처리할 것임
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

v = np.array([1,0,1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


하지만, x가 매우 크다면 파이썬의 반복문을 사용한다면 매우 느려질 수 있음  
이 경우는 벡터 v를 행렬 x의 각 행에 더하는 것으로 v를 여러 개 복사해 수직으로 행렬을 쌓고 그것을 x에 더하는 것과 동일함

In [156]:
vv = np.tile(v, (4,1))
print(vv)

y = x+ vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
